language: python
python:
  - 2.7
  - 3.3
  - 3.6
install:
  # setup.py test (script) fetches all test_require files, thus no pip needed
  #- pip install --use-mirrors -r test-requirements.txt
  - pip install coveralls
script:
  #nosetests -v
  coverage run --source=lesscpy setup.py test
after_success:
  coveralls
